# Generated by Django 4.1.2 on 2023-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Tittle', models.CharField(default='', max_length=25)),
                ('Video_Description', models.TextField(default='')),
                ('Video_Thumbline', models.FileField(upload_to='VideoThumblines')),
                ('Video', models.FileField(upload_to='Vidoes')),
            ],
        ),
    ]
